# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh github_package hadley/httr

script: ./travis-tool.sh run_tests

on_failure:
  - ./travis-tool.sh dump_logs

env:
  global:
    secure: "kK5UWXBMKs9GYLukBFMJwuE7Eujc+P5qHdieXhxOMvr2vSdEvuxIl6Y4xxlmpvTA6iWWhc9/k2FHfvIetOBwd/0LahYHerS+4qVgUEf8qYbACe/QL4B8QuLaQVMxkF35k9UJIKlj5LWzRcOhtB5qbj8S3A+A3Q5sBLVkvFSFrC0="

notifications:
  email:
    on_success: change
    on_failure: change
